### ISSUE TITLE
Unable to import library

### ISSUE THREAD

**Issue by jonathon-m** [tensor-labs/rocket-edit#1]
Angular is unable to find this library after install.
`Cannot find module 'rocket-edit'.`
I've confirmed that the files exist in node_modules, but still not working. 
Would love to try the library, please help.

**Comment by jonathon-m** [comment]
Installing version 0.1.3 resolved this. Only relevant to 0.1.4.

**Comment by yadavgvijay** [comment]
@jonathon-m Many thanks for reporting this bug. There was build error in library, we've fixed it in version 0.1.5.
