### ISSUE TITLE
(Save) not working

### ISSUE THREAD

**Issue by Mangdar** [tensor-labs/rocket-edit#4]
nothing happen when i call save function. am not sure is it bugs i using 0.1.8

**Comment by yadavgvijay** [comment]
@Mangdar I verified this issue on my development and test environment, unfortunately I can't reproduce this issue. Can you please let us know steps to reproduce it.

**Comment by Mangdar** [comment]
i just create new angular project and import your lib via npm 

app.module.ts
`import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';

import { RocketEditModule } from 'rocket-edit';

import { AppComponent } from './app.component';
@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    RocketEditModule,
    FormsModule,
    ReactiveFormsModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }`

app.component.html
`<div>
  <rocket-edit
  type="text"
  [(ngModel)]="editableText"
  (Save)="save($event)">
  </rocket-edit>
</div>`

**Comment by yadavgvijay** [comment]
@Mangdar Thanks for detailing issue. Can you please show us your package.json ?

**Comment by Mangdar** [comment]
{
  "name": "testrocket",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~8.1.2",
    "@angular/common": "~8.1.2",
    "@angular/compiler": "~8.1.2",
    "@angular/core": "~8.1.2",
    "@angular/forms": "~8.1.2",
    "@angular/platform-browser": "~8.1.2",
    "@angular/platform-browser-dynamic": "~8.1.2",
    "@angular/router": "~8.1.2",
    "rocket-edit": "^0.1.8",
    "rxjs": "~6.4.0",
    "tslib": "^1.9.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.801.2",
    "@angular/cli": "~8.1.2",
    "@angular/compiler-cli": "~8.1.2",
    "@angular/language-service": "~8.1.2",
    "@types/node": "~8.9.4",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "^5.0.0",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.4.3"
  }
}

**Comment by yadavgvijay** [comment]
@Mangdar I tried to reproduce issue with by building library with package.json you provided. Still, I can't reproduce it.

Can you please share your code by mailing us at tensorlabsindia@gmail.com
