### ISSUE TITLE
Select component does not initialize value from ngModel

### ISSUE THREAD

**Issue by jonathon-m** [tensor-labs/rocket-edit#5]
Until a new value is selected, the select component continues to show the default text. 
i.e. the initial value is not being set properly in the editor service.

**Comment by yadavgvijay** [comment]
If your selected value is Boolean then please make sure it is defined as 
selectedValue = false Or selectedValue = true
not like
selectedValue: false or selectedValue: true.

If still it won't work, try version 0.1.9 from npm
@jonathon-m Please verify and close the issue.

**Comment by jonathon-m** [comment]
Thanks for the reply @yadavgvijay. Setting as `selectedValue = false` is not practical when loading data from an API. But issue is solved in npm version 0.1.9!
